[package]
name = "pexport"
version = "0.1.0"
authors = ["Gijs de Jong <14833076+OxKitsune@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
